var argument = ["Is this the right room for an argument?",
"I've told you once.",
"No you haven't!",
"Yes I have.",
"When?",
"Just now.",
"No you didn't!",
"Yes I did!",
"You didn't!",
"I did!",
"You didn't!",
"I'm telling you, I did!",
"You did not!",
"Oh I'm sorry, is this a five minute argument, or the full half hour?",
"Ah! Just the five minutes.",
"Just the five minutes. Thank you.",
"Anyway, I did.",
"You most certainly did not!",
"Now let's get one thing quite clear: I most definitely told you!",
"Oh no you didn't!",
"Oh yes I did!",
"Oh no you didn't!",
"Oh yes I did!",
"Oh no you didn't!",
"Oh yes I did!",
"Oh no you didn't!",
"Oh yes I did!",
"Oh no you didn't!",
"Oh yes I did!",
"Oh no you didn't!",
"Oh yes I did!",
"No you DIDN'T!",
"Oh yes I did!",
"No you DIDN'T!",
"Oh yes I did!",
"No you DIDN'T!",
"Oh yes I did!",
"Oh look, this isn't an argument!",
"...",
"Yes it is!",
"No it isn't!",
"...",
"It's just contradiction!",
"No it isn't!",
"It IS!",
"It is NOT!",
"You just contradicted me!",
"No I didn't!",
"You DID!",
"No no no!",
"You did just then!",
"Nonsense!",
"Oh, this is futile!",
"...",
"No it isn't!",
"Yes it is!",
"...",
"I came here for a good argument!",
"Ah, no you didn't, you came here for an argument!",
"An argument isn't just contradiction.",
"Well! it CAN be!",
"No it can't!",
"An argument is a connected series of statements intended to establish a proposition.",
"No it isn't!",
"Yes it is! It isn't just contradiction.",
"Look, if I *argue* with you, I must take up a contrary position!",
"Yes but it isn't just saying 'no it isn't'.",
"Yes it is!",
"No it isn't!",
"Yes it is!",
"No it isn't!",
"Yes it is!",
"No it isn't! Argument is an intellectual process. Contradiction is just the automatic gainsaying of anything the other person says.",
"It is NOT!",
"It is!",
"Not at all!",
"It is!",
"*ding*",
"Thank you, that's it.",
"What?",
"That's it. Good morning.",
"But I was just getting interested!",
"I'm sorry, the five minutes is up.",
"That was never five minutes just now!",
"I'm afraid it was.",
"No it wasn't",
"...",
"I'm sorry, I'm not allowed to argue any more.",
"What?",
"If you want me to go on arguing, you'll have to pay for another five minutes.",
"But that was never five minutes just now!",
"Oh Come on!",
"This is ridiculous!",
"I told you, I'm not allowed to argue unless you pay!",
"Oh all right, there you are.",
"Thank you.",
"Well?",
"Well what?",
"That was never five minutes just now.",
"I told you, I'm not allowed to argue unless you've paid!",
"Well I just paid!",
"No you didn't!",
"I DID!!!",
"YOU didn't!",
"I DID!!!",
"YOU didn't!",
"I DID!!!",
"YOU didn't!",
"I DID!!!",
"YOU didn't!",
"I don't want to argue about it!",
"Well I'm very sorry but you didn't pay!",
"Ah hah! Well if I didn't pay, why are you arguing? Ah HAH! Gotcha!",
"No you haven't!",
"Yes I have! If you're arguing, I must have paid.",
"Not necessarily. I could be arguing in my spare time.",
"I've had enough of this!",
"No you haven't.",
"Oh shut up!"];